name: blog_commit_builder

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: hexo-builder
        run: |
          echo "Installing for hexo env"
          sudo apt install npm
          npm install -g hexo
          echo "Build hexo"
          hexo generate

  push_data:
    runs-on: ubuntu-latest

    steps:
      - name: Pushes to another repository
      - uses: cpina/github-action-push-to-another-repository@main
      - env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
          SUPER_USERNAME: ${{ secrets.USERNAME }}
          SUPER_EMAIL: ${{ secrets.EMAIL }}
        with:
          source-directory: 'public'
          destination-github-username: ${{ secrets.USERNAME }}
          destination-repository-name: 'public'
          user-email: ${{ secrets.EMAIL }}
          target-branch: main
